[package]
name = "compiler"
version = "0.1.0"
edition = "2024"

[lib]
name = "compiler"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
chrono = "0.4.44"
comemo = "0.5.1"
parking_lot = "0.12.5"
typst = "0.14.2"
typst-kit = { version = "0.14.2", features = ["fonts", "embed-fonts", "packages"] }
typst-pdf = "0.14.2"
typst-render = "0.14.2"
typst-syntax = "0.14.2"
typst-utils = "0.14.2"
